import {AfterViewInit, Component, Input, ViewChild} from '@angular/core';
import {MatPaginator} from "@angular/material/paginator";
import {MatTableDataSource} from "@angular/material/table";
import {SoftballHitter} from "../interfaces/softball";
import {formatDate} from "@angular/common";

@Component({
  selector: 'app-softball',
  templateUrl: './softball.component.html',
  styleUrls: ['./softball.component.scss']
})
export class SoftballComponent implements AfterViewInit {
  dataSource: MatTableDataSource<SoftballHitter>;
  @ViewChild(MatPaginator) paginator: MatPaginator | undefined;

  softballHitterData: SoftballHitter[] = [
    {
      name: 'Zach Batio',
      position: 'SS',
      games: 1,
      atBats: 1,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 1,
      battingAverage: 0.000,
      onBasePercentage: 1.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 1.000,
    },
    {
      name: 'Alexander Bae',
      position: '',
      games: 0,
      atBats: 0,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Tessa Berger',
      position: 'RF',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Alexander Caines',
      position: '',
      games: 0,
      atBats: 0,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Brandon Deleon',
      position: '3B',
      games: 1,
      atBats: 1,
      runs: 1,
      hits: 1,
      doubles: 1,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 1.000,
      onBasePercentage: 1.000,
      sluggingPercentage: 1.000,
      onBasePlusSlugging: 2.000,
    },
    {
      name: 'Audrey Dehler',
      position: 'RF',
      games: 1,
      atBats: 1,
      runs: 0,
      hits: 1,
      doubles: 1,
      triples: 0,
      homeruns: 0,
      rbis: 1,
      walks: 0,
      battingAverage: 1.000,
      onBasePercentage: 1.000,
      sluggingPercentage: 0.500,
      onBasePlusSlugging: 1.500,
    },
    {
      name: 'Declan Donohue',
      position: 'LF',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Ian Imhof',
      position: '3B',
      games: 1,
      atBats: 1,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Justin Imhof',
      position: 'CF',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 1,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.500,
      onBasePercentage: 0.500,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Kyra Kalliope',
      position: 'C',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Juliana Livieri',
      position: '2B',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 1,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 1,
      walks: 0,
      battingAverage: 0.500,
      onBasePercentage: 0.500,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.500,
    },
    {
      name: 'Kevin Patto',
      position: '',
      games: 0,
      atBats: 0,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Alyssa Pierce',
      position: '',
      games: 0,
      atBats: 0,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Zaq Perdomo',
      position: '1B',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Kenny Puleikis',
      position: 'SS',
      games: 1,
      atBats: 2,
      runs: 1,
      hits: 1,
      doubles: 0,
      triples: 1,
      homeruns: 0,
      rbis: 1,
      walks: 0,
      battingAverage: 0.500,
      onBasePercentage: 0.500,
      sluggingPercentage: 0.375,
      onBasePlusSlugging: 0.875,
    },
    {
      name: 'Jan Rara',
      position: 'CF',
      games: 1,
      atBats: 2,
      runs: 1,
      hits: 2,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 1.000,
      onBasePercentage: 1.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 1.000,
    },
    {
      name: 'Tony Rayas',
      position: '',
      games: 0,
      atBats: 0,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
    {
      name: 'Jonah Toch',
      position: 'P',
      games: 1,
      atBats: 2,
      runs: 0,
      hits: 2,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 1.000,
      onBasePercentage: 1.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 1.000,
    },
    {
      name: 'Jessica Uy',
      position: 'LF',
      games: 1,
      atBats: 1,
      runs: 0,
      hits: 0,
      doubles: 0,
      triples: 0,
      homeruns: 0,
      rbis: 0,
      walks: 0,
      battingAverage: 0.000,
      onBasePercentage: 0.000,
      sluggingPercentage: 0.000,
      onBasePlusSlugging: 0.000,
    },
  ]

  headers = [
    {label: 'Item ID', key: 'manufacturerItemId'},
    {label: 'Quantity', key: 'quantity'},
    {label: 'Purchase Order', key: 'purchaseOrder'},
  ];
  displayedColumns: string[] = ['name', 'games', 'atBats', 'runs', 'hits', 'doubles', 'triples', 'homeruns', 'rbis', 'walks', 'battingAverage',
    'onBasePercentage', 'sluggingPercentage', 'onBasePlusSlugging'];

  constructor() {
    this.dataSource = new MatTableDataSource<SoftballHitter>(this.softballHitterData);
  }

  ngAfterViewInit() {
    this.dataSource = new MatTableDataSource<SoftballHitter>(this.softballHitterData);
    // @ts-ignore
    this.dataSource.paginator = this.paginator;
  }

  getCurrDate() {
    return formatDate(new Date(), 'MM-dd-yy', 'en');
  }

  convertToPercentage(num: number) {
  }


}
